"""Bash Readline widget script generation."""

from __future__ import annotations

import shlex
import sys

from tmksh.shell.common import JSON_FIELD_PROGRAM, current_command_path


def render_bash_init(
    *,
    key_binding: str = r"\C-g",
    command_path: str | None = None,
    python_path: str | None = None,
) -> str:
    """Render the Bash widget script with safe runtime paths and key binding."""

    command = command_path or current_command_path()
    python = python_path or sys.executable
    binding = shlex.quote(f'"{key_binding}":__tmksh_widget')
    return (
        _BASH_TEMPLATE.replace("@@TMKSH_COMMAND@@", shlex.quote(command))
        .replace("@@TMKSH_PYTHON@@", shlex.quote(python))
        .replace("@@TMKSH_JSON_FIELD@@", JSON_FIELD_PROGRAM)
        .replace("@@TMKSH_BINDING@@", binding)
        .rstrip()
    )


_BASH_TEMPLATE = r"""# tmksh Bash integration. Generated by `tmksh init bash`.
# This script only fills READLINE_LINE. It never evaluates or executes AI output.
if [[ -z ${TMKSH_COMMAND:-} ]]; then
    TMKSH_COMMAND=@@TMKSH_COMMAND@@
fi
if [[ -z ${TMKSH_PYTHON:-} ]]; then
    TMKSH_PYTHON=@@TMKSH_PYTHON@@
fi

__tmksh_json_field() {
    "$TMKSH_PYTHON" -c '@@TMKSH_JSON_FIELD@@' "$1"
}

__tmksh_read_input() {
    local prompt="$1"
    # A separate TTY process consumes Enter without leaking it to outer Readline.
    REPLY="$("$TMKSH_COMMAND" _prompt --label "$prompt")"
}

__tmksh_widget() {
    local original_line="$READLINE_LINE"
    local original_point="$READLINE_POINT"
    local request=""
    local response=""
    local command=""
    local message=""
    local question=""
    local answer=""
    local REPLY=""
    local status=0
    local attempts=0

    printf '\n'
    if ! __tmksh_read_input 'tmksh> '; then
        READLINE_LINE="$original_line"
        READLINE_POINT="$original_point"
        return 0
    fi
    request="$REPLY"
    if [[ -z "${request//[[:space:]]/}" ]]; then
        READLINE_LINE="$original_line"
        READLINE_POINT="$original_point"
        return 0
    fi

    while (( attempts < 3 )); do
        response="$(
            printf '%s\0%s' "$request" "$original_line" \
                | "$TMKSH_COMMAND" suggest --input-format nul
        )"
        status=$?

        if (( status == 0 )); then
            command="$(printf '%s' "$response" | __tmksh_json_field command)"
            message="$(printf '%s' "$response" | __tmksh_json_field message)"
            if [[ -z "$command" ]]; then
                printf '%s\n' "${message:-tmksh did not return a command.}"
                READLINE_LINE="$original_line"
                READLINE_POINT="$original_point"
                return 0
            fi
            [[ -n "$message" ]] && printf '%s\n' "$message"
            READLINE_LINE="$command"
            READLINE_POINT=${#READLINE_LINE}
            return 0
        fi

        if (( status == 30 )); then
            question="$(printf '%s' "$response" | __tmksh_json_field clarification)"
            printf '%s\n' "需要澄清：${question:-请补充必要信息。}"
            if ! __tmksh_read_input '补充> '; then
                READLINE_LINE="$original_line"
                READLINE_POINT="$original_point"
                return 0
            fi
            answer="$REPLY"
            if [[ -z "${answer//[[:space:]]/}" ]]; then
                READLINE_LINE="$original_line"
                READLINE_POINT="$original_point"
                return 0
            fi
            request+=$'\n\n'"澄清问题：$question"$'\n'"用户补充：$answer"
            (( attempts += 1 ))
            continue
        fi

        message="$(printf '%s' "$response" | __tmksh_json_field message)"
        printf '%s\n' "${message:-tmksh 请求失败（退出码 $status）。}"
        READLINE_LINE="$original_line"
        READLINE_POINT="$original_point"
        return 0
    done

    printf '%s\n' '澄清次数过多，已保留原命令。'
    READLINE_LINE="$original_line"
    READLINE_POINT="$original_point"
}

if [[ $- == *i* ]]; then
    bind -x @@TMKSH_BINDING@@
fi
"""
