"""Fish commandline widget script generation."""

from __future__ import annotations

import shlex
import sys

from tmksh.shell.common import JSON_FIELD_PROGRAM, current_command_path


def render_fish_init(
    *,
    key_binding: str = r"\cg",
    command_path: str | None = None,
    python_path: str | None = None,
) -> str:
    """Render the Fish widget script with safe runtime paths and key binding."""

    command = command_path or current_command_path()
    python = python_path or sys.executable
    return (
        _FISH_TEMPLATE.replace("@@TMKSH_COMMAND@@", shlex.quote(command))
        .replace("@@TMKSH_PYTHON@@", shlex.quote(python))
        .replace("@@TMKSH_JSON_FIELD@@", JSON_FIELD_PROGRAM)
        .replace("@@TMKSH_BINDING@@", shlex.quote(key_binding))
        .rstrip()
    )


_FISH_TEMPLATE = r"""# tmksh Fish integration. Generated by `tmksh init fish`.
# This script only fills the Fish commandline. It never evaluates or executes AI output.
if not set -q TMKSH_COMMAND
    set -g TMKSH_COMMAND @@TMKSH_COMMAND@@
end
if not set -q TMKSH_PYTHON
    set -g TMKSH_PYTHON @@TMKSH_PYTHON@@
end

function __tmksh_json_field
    "$TMKSH_PYTHON" -c '@@TMKSH_JSON_FIELD@@' "$argv[1]"
end

function __tmksh_read_input
    set -l prompt "$argv[1]"
    "$TMKSH_COMMAND" _prompt --label "$prompt"
end

function __tmksh_widget
    set -l original_buffer (commandline)
    set -l original_cursor (commandline --cursor)
    set -l request (__tmksh_read_input 'tmksh> ')
    or begin
        commandline --replace "$original_buffer"
        commandline --cursor "$original_cursor"
        return 0
    end

    if test -z (string trim -- "$request")
        commandline --replace "$original_buffer"
        commandline --cursor "$original_cursor"
        return 0
    end

    set -l attempts 0
    while test $attempts -lt 3
        set -l response (printf '%s\0%s' "$request" "$original_buffer" \
            | "$TMKSH_COMMAND" suggest --input-format nul)
        set -l exit_status $status

        if test $exit_status -eq 0
            set -l generated_command (printf '%s' "$response" | __tmksh_json_field command)
            set -l message (printf '%s' "$response" | __tmksh_json_field message)
            if test -z "$generated_command"
                test -n "$message"; and printf '%s\n' "$message"
                commandline --replace "$original_buffer"
                commandline --cursor "$original_cursor"
                return 0
            end
            test -n "$message"; and printf '%s\n' "$message"
            commandline --replace "$generated_command"
            commandline --cursor (string length -- "$generated_command")
            return 0
        end

        if test $exit_status -eq 30
            set -l question (printf '%s' "$response" | __tmksh_json_field clarification)
            test -n "$question"; or set question '请补充必要信息。'
            printf '%s\n' "需要澄清：$question"
            set -l answer (__tmksh_read_input '补充> ')
            or begin
                commandline --replace "$original_buffer"
                commandline --cursor "$original_cursor"
                return 0
            end
            if test -z (string trim -- "$answer")
                commandline --replace "$original_buffer"
                commandline --cursor "$original_cursor"
                return 0
            end
            set request "$request\n\n澄清问题：$question\n用户补充：$answer"
            set attempts (math $attempts + 1)
            continue
        end

        set -l message (printf '%s' "$response" | __tmksh_json_field message)
        test -n "$message"; or set message "tmksh 请求失败（退出码 $exit_status）。"
        printf '%s\n' "$message"
        commandline --replace "$original_buffer"
        commandline --cursor "$original_cursor"
        return 0
    end

    printf '%s\n' '澄清次数过多，已保留原命令。'
    commandline --replace "$original_buffer"
    commandline --cursor "$original_cursor"
end

if status is-interactive
    bind @@TMKSH_BINDING@@ __tmksh_widget
end
"""
