"""Zsh ZLE widget script generation."""

from __future__ import annotations

import shlex
import sys

from tmksh.shell.common import JSON_FIELD_PROGRAM, current_command_path


def render_zsh_init(
    *,
    key_binding: str = "^G",
    command_path: str | None = None,
    python_path: str | None = None,
) -> str:
    """Render the Zsh widget script with safe runtime paths and key binding."""

    command = command_path or current_command_path()
    python = python_path or sys.executable
    return (
        _ZSH_TEMPLATE.replace("@@TMKSH_COMMAND@@", shlex.quote(command))
        .replace("@@TMKSH_PYTHON@@", shlex.quote(python))
        .replace("@@TMKSH_JSON_FIELD@@", JSON_FIELD_PROGRAM)
        .replace("@@TMKSH_BINDING@@", shlex.quote(key_binding))
        .rstrip()
    )


_ZSH_TEMPLATE = r"""# tmksh Zsh integration. Generated by `tmksh init zsh`.
# This script only fills BUFFER. It never evaluates or executes AI output.
if [[ -z ${TMKSH_COMMAND:-} ]]; then
    typeset -g TMKSH_COMMAND=@@TMKSH_COMMAND@@
fi
if [[ -z ${TMKSH_PYTHON:-} ]]; then
    typeset -g TMKSH_PYTHON=@@TMKSH_PYTHON@@
fi

__tmksh_json_field() {
    "$TMKSH_PYTHON" -c '@@TMKSH_JSON_FIELD@@' "$1"
}

__tmksh_zle_message() {
    zle -M "$1" 2>/dev/null || print -r -- "$1"
}

__tmksh_read_input() {
    local prompt="$1"
    REPLY=""
    if (( $+ZLE_STATE )); then
        local saved_buffer="$BUFFER"
        local -i saved_cursor=$CURSOR
        BUFFER=""
        CURSOR=0
        zle -M "$prompt"
        if ! zle recursive-edit; then
            BUFFER="$saved_buffer"
            CURSOR=$saved_cursor
            zle -M ""
            return 1
        fi
        REPLY="$BUFFER"
        BUFFER="$saved_buffer"
        CURSOR=$saved_cursor
        zle -M ""
        return 0
    fi
    IFS= read -r "REPLY?$prompt"
}

__tmksh_widget() {
    local original_buffer="$BUFFER"
    local -i original_cursor=$CURSOR
    local request=""
    local response=""
    local command=""
    local message=""
    local question=""
    local answer=""
    local REPLY=""
    local -i exit_status=0
    local -i attempts=0

    if ! __tmksh_read_input 'tmksh> '; then
        BUFFER="$original_buffer"
        CURSOR=$original_cursor
        return 0
    fi
    request="$REPLY"
    if [[ -z "${request//[[:space:]]/}" ]]; then
        BUFFER="$original_buffer"
        CURSOR=$original_cursor
        return 0
    fi

    while (( attempts < 3 )); do
        response="$(
            printf '%s\0%s' "$request" "$original_buffer" \
                | "$TMKSH_COMMAND" suggest --input-format nul
        )"
        exit_status=$?

        if (( exit_status == 0 )); then
            command="$(printf '%s' "$response" | __tmksh_json_field command)"
            message="$(printf '%s' "$response" | __tmksh_json_field message)"
            if [[ -z "$command" ]]; then
                __tmksh_zle_message "${message:-tmksh did not return a command.}"
                BUFFER="$original_buffer"
                CURSOR=$original_cursor
                return 0
            fi
            BUFFER="$command"
            CURSOR=${#BUFFER}
            [[ -n "$message" ]] && __tmksh_zle_message "$message"
            return 0
        fi

        if (( exit_status == 30 )); then
            question="$(printf '%s' "$response" | __tmksh_json_field clarification)"
            __tmksh_zle_message "需要澄清：${question:-请补充必要信息。}"
            if ! __tmksh_read_input '补充> '; then
                BUFFER="$original_buffer"
                CURSOR=$original_cursor
                return 0
            fi
            answer="$REPLY"
            if [[ -z "${answer//[[:space:]]/}" ]]; then
                BUFFER="$original_buffer"
                CURSOR=$original_cursor
                return 0
            fi
            request+=$'\n\n'"澄清问题：$question"$'\n'"用户补充：$answer"
            (( attempts += 1 ))
            continue
        fi

        message="$(printf '%s' "$response" | __tmksh_json_field message)"
        __tmksh_zle_message "${message:-tmksh 请求失败（退出码 $exit_status）。}"
        BUFFER="$original_buffer"
        CURSOR=$original_cursor
        return 0
    done

    __tmksh_zle_message '澄清次数过多，已保留原命令。'
    BUFFER="$original_buffer"
    CURSOR=$original_cursor
}

if [[ -o interactive ]]; then
    zle -N __tmksh_widget
    bindkey @@TMKSH_BINDING@@ __tmksh_widget
fi
"""
