"""Zsh ZLE widget script generation."""

from __future__ import annotations

import shlex
import sys

from tmksh.shell.common import JSON_FIELD_PROGRAM, current_command_path


def render_zsh_init(
    *,
    key_binding: str = "^G",
    command_path: str | None = None,
    python_path: str | None = None,
) -> str:
    """Render the Zsh widget script with safe runtime paths and key binding."""

    command = command_path or current_command_path()
    python = python_path or sys.executable
    return (
        _ZSH_TEMPLATE.replace("@@TMKSH_COMMAND@@", shlex.quote(command))
        .replace("@@TMKSH_PYTHON@@", shlex.quote(python))
        .replace("@@TMKSH_JSON_FIELD@@", JSON_FIELD_PROGRAM)
        .replace("@@TMKSH_BINDING@@", shlex.quote(key_binding))
        .rstrip()
    )


_ZSH_TEMPLATE = r"""# tmksh Zsh integration. Generated by `tmksh init zsh`.
# This script only fills BUFFER. It never evaluates or executes AI output.
if [[ -z ${TMKSH_COMMAND:-} ]]; then
    typeset -g TMKSH_COMMAND=@@TMKSH_COMMAND@@
fi
if [[ -z ${TMKSH_PYTHON:-} ]]; then
    typeset -g TMKSH_PYTHON=@@TMKSH_PYTHON@@
fi

autoload -Uz add-zsh-hook
typeset -g TMKSH_LAST_COMMAND=""

__tmksh_capture_command_start() {
    typeset -g TMKSH_LAST_COMMAND="$1"
    typeset -g TMKSH_PENDING_COMMAND="$1"
    typeset -g TMKSH_PENDING_CWD="$PWD"
}

__tmksh_capture_command_end() {
    local -i exit_status=$?
    if (( exit_status != 0 )) && [[ -n ${TMKSH_PENDING_COMMAND:-} ]]; then
        typeset -g TMKSH_LAST_FAILED_COMMAND="$TMKSH_PENDING_COMMAND"
        typeset -g TMKSH_LAST_FAILED_STATUS="$exit_status"
        typeset -g TMKSH_LAST_FAILED_CWD="${TMKSH_PENDING_CWD:-$PWD}"
        typeset -g TMKSH_LAST_FAILED_SHELL="zsh"
    fi
    typeset -g TMKSH_PENDING_COMMAND=""
    typeset -g TMKSH_PENDING_CWD=""
    return $exit_status
}

add-zsh-hook -d preexec __tmksh_capture_command_start 2>/dev/null
add-zsh-hook preexec __tmksh_capture_command_start
# This hook must run first so another precmd hook cannot overwrite `$?`.
precmd_functions=(${precmd_functions:#__tmksh_capture_command_end})
precmd_functions=(__tmksh_capture_command_end $precmd_functions)

__tmksh_json_field() {
    "$TMKSH_PYTHON" -c '@@TMKSH_JSON_FIELD@@' "$1"
}

__tmksh_print_message() {
    if (( $+ZLE_STATE )); then
        zle -I
    fi
    print -r -- "$1"
}

__tmksh_read_input() {
    local prompt="$1"
    REPLY=""
    if (( $+ZLE_STATE )); then
        local saved_buffer="$BUFFER"
        local -i saved_cursor=$CURSOR
        BUFFER=""
        CURSOR=0
        zle -M "$prompt"
        if ! zle recursive-edit; then
            BUFFER="$saved_buffer"
            CURSOR=$saved_cursor
            zle -M ""
            return 1
        fi
        REPLY="$BUFFER"
        BUFFER="$saved_buffer"
        CURSOR=$saved_cursor
        zle -M ""
        return 0
    fi
    IFS= read -r "REPLY?$prompt"
}

__tmksh_widget() {
    local original_buffer="$BUFFER"
    local -i original_cursor=$CURSOR
    local request=""
    local response=""
    local kind=""
    local command=""
    local message=""
    local question=""
    local clarification_answer=""
    local REPLY=""
    local -i exit_status=0
    local -i clarification_count=0
    local failed_command="${TMKSH_LAST_FAILED_COMMAND:-}"
    local failed_status="${TMKSH_LAST_FAILED_STATUS:-}"
    local failed_cwd="${TMKSH_LAST_FAILED_CWD:-}"
    local failed_shell="${TMKSH_LAST_FAILED_SHELL:-}"
    local last_command="${TMKSH_LAST_COMMAND:-}"

    if ! __tmksh_read_input 'tmksh> '; then
        BUFFER="$original_buffer"
        CURSOR=$original_cursor
        return 0
    fi
    request="$REPLY"
    if [[ -z "${request//[[:space:]]/}" ]]; then
        BUFFER="$original_buffer"
        CURSOR=$original_cursor
        return 0
    fi

    while true; do
        response="$(
            printf '%s\0%s\0%s\0%s\0%s\0%s\0%s' \
                "$request" "$original_buffer" "$failed_command" \
                "$failed_status" "$failed_cwd" "$failed_shell" "$last_command" \
                | "$TMKSH_COMMAND" suggest --input-format nul
        )"
        exit_status=$?
        kind="$(printf '%s' "$response" | __tmksh_json_field kind)"

        if (( exit_status == 0 )) && [[ "$kind" == "command" ]]; then
            command="$(printf '%s' "$response" | __tmksh_json_field command)"
            message="$(printf '%s' "$response" | __tmksh_json_field message)"
            if [[ -z "$command" ]]; then
                __tmksh_print_message "${message:-tmksh did not return a command.}"
                BUFFER="$original_buffer"
                CURSOR=$original_cursor
                return 0
            fi
            [[ -n "$message" ]] && __tmksh_print_message "$message"
            BUFFER="$command"
            CURSOR=${#BUFFER}
            return 0
        fi

        if (( exit_status == 0 )) && [[ "$kind" == "answer" ]]; then
            message="$(printf '%s' "$response" | __tmksh_json_field message)"
            __tmksh_print_message "${message:-tmksh did not return a usable result.}"
            BUFFER="$original_buffer"
            CURSOR=$original_cursor
            return 0
        fi

        if (( exit_status == 30 )) && [[ "$kind" == "clarification" ]]; then
            question="$(printf '%s' "$response" | __tmksh_json_field clarification)"
            __tmksh_print_message "需要澄清：${question:-请补充必要信息。}"
            if (( clarification_count >= 3 )); then
                __tmksh_print_message '澄清次数过多，已保留原命令。'
                BUFFER="$original_buffer"
                CURSOR=$original_cursor
                return 0
            fi
            if ! __tmksh_read_input '补充> '; then
                BUFFER="$original_buffer"
                CURSOR=$original_cursor
                return 0
            fi
            clarification_answer="$REPLY"
            if [[ -z "${clarification_answer//[[:space:]]/}" ]]; then
                BUFFER="$original_buffer"
                CURSOR=$original_cursor
                return 0
            fi
            request+=$'\n\n'"澄清问题：$question"$'\n'"用户补充：$clarification_answer"
            (( clarification_count += 1 ))
            continue
        fi

        message="$(printf '%s' "$response" | __tmksh_json_field message)"
        __tmksh_print_message "${message:-tmksh 请求失败（退出码 $exit_status）。}"
        BUFFER="$original_buffer"
        CURSOR=$original_cursor
        return 0
    done
}

if [[ -o interactive ]]; then
    zle -N __tmksh_widget
    bindkey @@TMKSH_BINDING@@ __tmksh_widget
fi
"""
